spring:
  data:
    mongodb:
      port: 27017
      host: 192.168.56.102
      database: myDatabase
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG